### ISSUE TITLE
Avoid spam

### ISSUE THREAD

**Issue by HasaanAhmad** [Abstract-Systems/public-wall#3]
A single person should not be able to post more than 2 or 3 Messages on wall per day . -Feature

**Comment by mujtaba-io** [comment]
Yes. Ill push login/signup, then we can add this.

**Comment by mujtaba-io** [comment]
@HasaanAhmad yar login signup app ko thora complex krdega, it is intended for simplicity and one-page app. -- I think posting process ko tedious krlena bhtr hoga. like captcha + wait for 5 minutes per session + a small quiz + some shit to make people not give a fuck by spamming... later we can add login signup, but for now, lets move it quickly to production level by working on core features.

**Comment by mujtaba-io** [comment]
yess... its done. i made logn bcz there was no way to map posts to users other than by login, so the issue is resolved.
